### ISSUE TITLE
Distinguishing from comparison operators

### ISSUE THREAD

**Issue by smaili** [atom/language-javascript#188]
I've noticed that these two rules use the same grouping:

```cson
  {
    'match': '(?<!\\.)\\b(delete|in|of|instanceof|new|typeof|void)(?!\\s*:)\\b'
    'name': 'keyword.operator.js'
  }
  {
    'match': '!=|!==|<=|>=|<<=|>>=|>>>=|\\*=|(?<!\\()/=|%=|\\+=|\\-=|&=|\\^=|!|%|&|\\*|\\-\\-|\\-|\\+\\+|\\+|~|===|==|=|<>|<|>|!|&&|\\|\\||\\?|\\:|\\^'
    'comment': 'match 2-character operator first'
    'name': 'keyword.operator.js'
  }
```

By using the same groups for both, we can't have syntax highlighting be applied to keywords like `delete` and `typeof`.  What would be the best way to distinguish these?  Maybe remove the `keyword` class from the second group of operators?

**Comment by chbk** [comment]
How about:

- `keyword.operator.language.js` for `delete`, `in`, `of`, `instanceof`, `new`, `typeof`, `void`
- `keyword.operator.js` for `=`, `!`, `<`, `>`, `+`, `-`, `%`, and other symbols

Since the `language` class is used by `true`, `false`, `null`, `super`, `this`, `Infinity`, `NaN`, and `undefined`, it would fit nicely with the operators.

**Comment by smaili** [comment]
I like it :+1:

**Comment by MaximSokolov** [comment]
> Since the language class is used by true, false, null, super, this, Infinity, NaN, and undefined, it would fit nicely with the operators.

Disagree. `variable.language` scope separate user defined variables from language variables. Scopes should be semantic.  I don't see any reason why `delete, in, of, instanceof, new, typeof, void` are **language** operators and `*=, !, <, >, +, -, %, and other symbols` are not. 

 I [proposed](https://github.com/atom/docs/pull/114) `keyword.operator.comparison` , `keyword.operator.arithmetic` , `keyword.operator.logical` (and others) scopes. Seems these scopes   are suitable for this goal.

>
variable
  - parameter
  - language — **reserved language variables like this, super, self, etc.**
  - other

**Comment by chbk** [comment]
> I don't see any reason why delete, in, of, instanceof, new, typeof, void are language operators and *=, !, <, >, +, -, %, and other symbols are not.

In that case why use a "language" scope at all, if it's so broad? A "reserved" scope would be less ambiguous, and it could be shared with non-arithmetic operators.

IMO the doc should take into account which categories are commonly highlighted together, since that's the main purpose of scopes. `delete`, `in`, `of`, `instanceof`, `new`, `typeof`, `void` are usually highlighted because they are reserved words not just operators.

**Comment by MaximSokolov** [comment]
> In that case why use a "language" scope at all, if it's so broad?

`language` scope isn't  broad. `variable.language` and `constant.language` scopes have specific goal: match variables/contants provided by language. e.g `true` is constant *language* constant while `123` is not.

> IMO the doc should take into account which categories are commonly highlighted together, since that's the main purpose of scopes. `delete`, `in`, `of`, `instanceof`, `new`, `typeof`, `void` are usually highlighted because they are reserved words not just operators.

I agree. Scopes should have common attribute. However these scopes don't have nothing in common. Some of these "operators" aren't even a "keyword.operator". I think we shouldn't change such scopes until we would have a clear documentation. Otherwise would be much more troubles with syntax highlighting because of misunderstanding like in this issue.

**Comment by VitaliyR** [comment]
@MaximSokolov hello. Actually there are already troubles with highlighting. I really wanna make logical operators to be white (e.g.) and instanceof/delete etc to be orange but for now - I can't (actually I have a start script which make that job for me, but it is not a solution)

**Comment by MaximSokolov** [comment]
IMO scopes should be:
`in`, `of`, `&&`, `||`, `!` — `keyword.operator.logical`
`~`, `&`, `^`, `|` — `keyword.operator.logical.bitwise`
`*`, `-`, `+`, `%` — `keyword.operator.arithmetic`
`<=`, `>=`, `!=`, `!==`, `===`, `==`, `<`, `>` — `keyword.operator.comparison`
`=` — `keyword.operator.assignment`
`/=`, `%=`. `+=` `-=`, `*=`, `**=` — `keyword.operator.assignment.augmented`
`|=`, `&=`, `^=`, `<<=`, `>>=`, `>>>=` — `keyword.operator.assignment.augmented.bitwise`
`--` — `keyword.operator.decrement`
`++` — `keyword.operator.increment`
`void` — `storage.type`
`delete`, `new`, `instanceof`, `typeof` — don't known. But not a `keyword.operator.language`! Let it be just `keyword.operator`

**Comment by Pauan** [comment]
@MaximSokolov I generally agree with your list, except... I'm curious why you listed `in` and `of` as being `keyword.operator.logical`

In my opinion, `in` and `of` should not be `keyword.operator.logical`, but should have the same rule as `delete`, `new`, `typeof`, etc.

**Comment by MaximSokolov** [comment]
> The in operator returns true if the specified property is in the specified object.

```js
result = property in object
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in
https://msdn.microsoft.com/en-us/library/9k25hbz2(v=vs.94).Aspx

Couldn't find any specific for "of" operator. I suppose `i of arr` returns boolean:
```js
for (let i of arr) {}
```
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of

**Comment by chbk** [comment]
I agree with @Pauan, why put `in` and `of` in `keyword.operator.logical` but leave out `instanceof`?
Those aren't even logical operators: [JavaScript Logical Operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators)

I just noticed that `as`, `await`, `break`, `case`, `catch`, `continue`, `default` `do`, `else`, `finally`, `for`, `if`, `import`, `from`, `package`, `return`, `switch`, `throw`, `try`, `while`, `with`, `yield` are all `keyword.control`

I agree that `void` should be set apart, perhaps `in`, `of`, `instanceof`, and `typeof` also need their own scope, but why weren't `delete` and  `new` added to `keyword.control`?

**Comment by chbk** [comment]
I suggest you replace `augmented` with `alteration`. It would fit better with the other scope names.

**Comment by chbk** [comment]
@MaximSokolov [JavaScript Reserved Keywords](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_keywords_as_of_ECMAScript_6)
I suggest adding a `reserved` scope that can be shared by different tokens.

**Comment by MaximSokolov** [comment]
> why put `in` and `of` in `keyword.operator.logical` but leave out `instanceof`?

I was mistaken because of [Python definition](https://github.com/atom/language-python/blob/802aa701b541cb3b34d27b4050d966a09dd6ba1b/grammars/python.cson#L113-L115) of logical operators ([formal difinition](https://en.wikipedia.org/wiki/Logical_connective))  You are right. `in`, `of`, `instanceof` are not logical operators. 

>  but why weren't delete and new added to keyword.control?

Good question. Actually at first by
> Some of these "operators" aren't even a `keyword.operator`

I mean `void`, `new`, `delete`. However [read](http://manual.macromates.com/en/language_grammars#naming_conventions) `keyword.control` definition:

>  related to flow control

Then look at list of scopes in your comment. `new`, `delete` aren't related  to flow control.

> I suggest you replace `augmented` with `alteration`...

Ruby, Python, Go already use `keyword.operator.assignment.augmented`

> ...It would fit better with the other scope names.

What *other scope names*?

> I suggest adding a reserved scope that can be shared by different tokens.

Give examples of *unreserved tokens* please. Not fully understand you

**Comment by chbk** [comment]
> new, delete aren't related to flow control.

Yes I agree that `delete` and `new` aren't flow control keywords, I edited my comment shortly after posting.

> Ruby, Python, Go already use keyword.operator.assignment.augmented

I wasn't suggesting changing it right now. I feel it's something to consider while working on the docs.

> What other scope names?

I mean that `comparison`, `assignment`, `decrement`, `increment`, etc. are all nouns, yet `augmented` is an adjective. Why? But more importantly `augmented` is too specific, using `alteration` would be wiser as it doesn't imply the variable is being increased.

> Give examples of unreserved tokens please.

IMO all keywords that are [listed here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_keywords_as_of_ECMAScript_6) should share a `reserved` scope. Anything not in that list is "unreserved" in the sense that it's not a word used for language functionality.

**Comment by MaximSokolov** [comment]
> I mean that `comparison`, `assignment`, `decrement`, `increment`, etc. are all nouns, yet `augmented` is an adjective. Why?

Seems "augmented" is a passive verb, I am not a native speaker though. Since there are `string.quoted`, `variable.interpolated`, etc. "augmented" looks good to me

> Why? But more importantly `augmented` is too specific, using `alteration` would be wiser as it doesn't imply the variable is being increased.

It is. It means "assignment augmented by another operator" Why it shouldn't be specific?

> > Give examples of unreserved tokens please.

> IMO all keywords that are [listed here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_keywords_as_of_ECMAScript_6) should share a reserved scope. Anything not in that list is "unreserved" in the sense that it's not a word used for language functionality.

"Reserved" keywords there means that they cannot be used as identifiers. `reserved` will not append any useful information about language symbol.

**Comment by chbk** [comment]
> It means "assignment augmented by another operator"

That makes much more sense, I didn't interpret it that way.

> "Reserved" keywords there means that they cannot be used as identifiers. reserved will not append any useful information about language symbol.

I see what you mean, but you also said scopes should have common attributes, and even though it doesn't add information, it does separate `delete`, `in`, `of`, `instanceof`, `new`, `typeof` from other operators, and makes it extremely convenient to apply a single syntax rule to all reserved words at once.

**Comment by MaximSokolov** [comment]
All keywords from grammar are "reserved". You can't use `&&` as identifier either.
