### ISSUE TITLE
Wrong highlighting for a hash variables

### ISSUE THREAD

**Issue by xpepermint** [atom/language-javascript#336]
<img width="439" alt="screen shot 2016-03-16 at 6 27 46 pm" src="https://cloud.githubusercontent.com/assets/174279/13822186/efe587e4-eba4-11e5-9567-b53d346f2aed.png">

As you can see the `client.customValue` is colored in red but should be white.

**Comment by 50Wliu** [comment]
Why should it be white?

**Comment by xpepermint** [comment]
Why should the same variable be colored differently? It's not logical (`client` should be white). The red part of the `client` seems like a totally unrelated object.
Other text editors like Sublime and Cloude9 will handle this as explained. I found https://atom.io/packages/language-javascript-better package which corrects the behaviour but I would expect this issue to be resolved here resolved here as well.

**Comment by 50Wliu** [comment]
Ok, thanks for clarifying.

> The red part of the client seems like a totally unrelated object.

This is definitely true, and `language-javascript` identifies them as separate as well: `client` is `variable.other.object.js` while `customValue` is `variable.other.property.js`.  The syntax theme you're using (which seems to be One Dark Syntax) just chose to color the two identically.

As for the inconsistencies in the `client` highlighting, that is because language-javascript is not yet advanced enough to capture all variables yet (hence why the `client` in `let/return client` is simply tagged as `source.js`).  The end goal we're going for is to have all three `clients` to be correctly tokenized as variables.  The reason language-javascript-better highlights everything as white is because it's more-or-less a fork of language-javascript that hasn't been updated since October, which is before we got tokenization of objects/properties working.

If on the other hand you don't want any special highlighting for variables, you can try following the instructions here: https://github.com/atom/one-dark-syntax/issues/60#issuecomment-172628426.  A discussion about the "over-redness" of one-dark is also occurring at https://github.com/atom/one-dark-syntax/issues/54.

Hope that helps!

**Comment by xpepermint** [comment]
I don't like hacking my best friend (text editor). Also related: https://github.com/atom/language-javascript/issues/258

**Comment by 50Wliu** [comment]
Atom *is* billed as "A hackable text editor" :stuck_out_tongue:.  Is it ok with you if I close this in favor of #258?

**Comment by xpepermint** [comment]
ok ;)
