### ISSUE TITLE
#282 regression

### ISSUE THREAD

**Issue by alexandernst** [atom/language-javascript#338]
PR #282 introduced a bug/regression.

![](http://s22.postimg.org/ftgiw7kn5/image.png)

**Comment by jrburke** [comment]
Thanks for the heads up. I am traveling for the next couple of days but will look into it after that.

**Comment by jrburke** [comment]
Looking more into this, the CSS parsing is grabbing more of the template string process such that the ${} expression interpolation matches do not work, and it gets confused.

To solve it would likely mean modifying the CSS parsing in language-css, but I think it will be difficult to do since both CSS and the expression interpolation both treat curly braces as very significant.

So to fix, in #341 I removed the CSS tagged template parsing. The HTML tagged template parsing does not suffer from this since curly braces are not significant for HTML.

**Comment by bcomnes** [comment]
The Babel-ES6 package seems to support css template strings still.  Is there something we can port over from there possibly?

**Comment by 50Wliu** [comment]
Yes, I've been thinking that this might still possible if the problems with the braces are fixed.  I have not had time to look at it yet.  We cannot use what language-babel is using because they have a [custom CSS language file](https://github.com/gandm/language-babel/blob/673452bad230c8189b58f49eb6827445b778a4ca/grammars/css.json) rather than using language-css.
