### ISSUE TITLE
`var` and `function` are keywords

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/language-javascript#47]
In Atom's developer tools I found `var` and `function` are treated as ".storage.modifier" and ".storage.function".

But according to ECMAScript 5.1, `var` and `function` are keywords:
http://www.ecma-international.org/ecma-262/5.1/#sec-7.6.1.1

**Comment by braver** [comment]
@schmitzjake It's not necessarily an issue of words getting the wrong color. It works, but the classification might be considered incorrect if you're going to be strict about it. Classifying `var` and `function` under `storage` instead of `keyword` is consistent with similar structures in php, c, etc. It might not be correct as per the es5 document, so @zhanzhenzhen might have a point. In practice though, I doubt it matters?

**Comment by 50Wliu** [comment]
So is there a general consensus on whether or not this should be fixed, or just left as a wontfix?  I'm not too sure there'll be that many benefits since syntax packages will have to adapt to the new tokenization.

**Comment by braver** [comment]
Lots of themes will have worked around this if they think it important. So if you were to change it, it'd be nice to communicate and allow some time for theme authors to react. However, I would propose either doing a full audit and match the package to ES spec, or leaving as is. Reacting to specific mismatches like this would just turn it into a moving target for theme authors.

**Comment by thomasjo** [comment]
I agree with @braver on this. I personally think this (and several other language packages) should be rewritten with ES6/ES2015, but that's a pretty hefty undertaking so unlikely to be done anytime soon. Hence `wontfix` is probably reasonable?

**Comment by MaximSokolov** [comment]
I assume Atom follows TextMate [naming conventions(section 12.4)](https://manual.macromates.com/en/language_grammars) of scope selectors.
 Otherwise it must be to create a syntax rule for each language.
So according naming conventions `var` and `function` are **not** keywords:
- storage — things relating to “storage”.
  * type — the type of something, class, **function**, int, **var**, etc.
  * modifier — a storage modifier like static, final, abstract, etc.

**Comment by Victorystick** [comment]
Agreed. `wontfix` send like a reasonable resolution.

**Comment by zhanzhenzhen** [comment]
Agree. Just found Atom uses the same naming conventions.
