### ISSUE TITLE
`const` has a different class from `var` and `let`

### ISSUE THREAD

**Issue by kaicataldo** [atom/language-javascript#471]
`const` currently has the `modifier` class as opposed to the `type` class that `var` and `let` do, leading to `const` being highlighted differently. Is this intentional? It would make a lot more sense to me if they had the same classes and were styled the same.

<img width="849" alt="screen shot 2016-12-11 at 8 49 13 pm" src="https://cloud.githubusercontent.com/assets/7041728/21085758/7aed541c-bfe3-11e6-97db-53c57536eecc.png">
<img width="793" alt="screen shot 2016-12-11 at 8 49 45 pm" src="https://cloud.githubusercontent.com/assets/7041728/21085759/7aee1d0c-bfe3-11e6-8a8a-f265319b8fba.png">

Happy to look into making a PR for this, if the team is amenable to this change.

**Comment by Alhadis** [comment]
Speaking as a grammar developer, I can attest that `storage.modifier` is a semantically inaccurate choice of scope, too.

It's supposed to be used for tokens like `public` or `protected` which *modify* how a value is stored/represented by the language.

So `const` should actually have the same scopes, because it fills the same lexical role as `let` and `var` do - named data assignment.

**Comment by 50Wliu** [comment]
This was probably copied over from other languages, where const is actually a modifier (like in Java).  So yeah, I'm ok with this change.

**Comment by Alhadis** [comment]
Are you implying JavaScript ever borrowed anything from Java?

COME ON SON.
