### ISSUE TITLE
Missing identation after a control statement without brackets

### ISSUE THREAD

**Issue by madakk** [atom/language-javascript#474]
If you type a control statement without opening brackets and hit enter, the indentation level is maintained rather than being increased one level:

![js_indent](https://cloud.githubusercontent.com/assets/24660923/21467214/cc0be4ba-c9e5-11e6-9b6c-803b5cf8a37d.gif)

I suspect this could be desirable if one was using brackets "BSD" style:
```
if (2>1)
{
  code;
}
```
Which I think could be handled by detecting the open bracket at the beggining of the line and immediately decreasing indentation. I don't know if the core supports this type of behavior, I'm not aware of the specifics of how auto indentation works. Otherwise, this could also be a setting for your preferred indentation style.

Furthermore, there's a related issue with the indentation of closing brackets involving a similar situation:

![js_indent2](https://cloud.githubusercontent.com/assets/24660923/21467246/b4ed3d3c-c9e6-11e6-85ea-499da230f341.gif)

This appears to be because the closing bracket always decreases indentation by one level. The correct behavior should be to return to the indentation level of the opening bracket, regardless of the current indentation. Again I'm not sure if this is a language-javascript level issue, or a more general core issue.

**Comment by lee-dohm** [comment]
Thank you for your submission!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
