### ISSUE TITLE
export default async

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/language-javascript#563]
```js
export default async ()=>{};
let a = async ()=>{};
```

The first `async` isn't highlighted as a keyword.

**Comment by TangSteven** [comment]
Appears to be fixed in version 0.128.8

**Comment by rsese** [comment]
Thanks for the report @zhanzhenzhen and thanks for pointing out that this is fixed with Tree-sitter @TangSteven :bow:

We're migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/) which will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

Thanks again!
