### ISSUE TITLE
let keyword syntax

### ISSUE THREAD

**Issue by Extarys** [atom/language-javascript#573]
`let` keyword have no style applied to it but `const` does.
Is this the right repo to report this? I have this issue with all themes so I figured it must be the language-javascript package that doesn't recognize this.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---
Note that I'm unable to reproduce this.

**Comment by Extarys** [comment]
Well, that is embarassing. After restarting atom in safe mode and tried, I did it again in normal mode and it's working.... Hmmmm.... Thanks anyway - will fill the template next time for sure!
