### ISSUE TITLE
Template string highlight issue with singel quote

### ISSUE THREAD

**Issue by George3d6** [atom/language-javascript#580]
When a template string contains a single quote, such as:

`` `The field ${name} doesn't exist ` ``, the javascript highlighter will highlight everything after the `'` as a string. I'm sure this is a well known issue but it's very hard to grep through it through the issues since it deal with two escape characters -_-.

Is there an easy fix for this ? Might this be due to a different package ?

**Comment by 50Wliu** [comment]
No repro:
![javascript-template-string-single-quote](https://user-images.githubusercontent.com/2766036/41324465-a5c474b4-6e82-11e8-9eb9-ba00c0dec303.png)
***
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
