### ISSUE TITLE
Incorrect indentation when using flow and tree-sitter

### ISSUE THREAD

**Issue by IanVS** [atom/language-javascript#603]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the `Flow Javascript` grammar with tree-sitter enabled, I notice that parenthesis are not always outdented correctly, whereas they are when using `Javascript`.  Here are some examples (taken during safe mode):

#### Javascript (correct)
![javascript](https://user-images.githubusercontent.com/4616705/46761897-b993b200-cca3-11e8-820c-7c47309e25d8.gif)

#### Flow Javascript (incorrect)
![flow](https://user-images.githubusercontent.com/4616705/46761953-d334f980-cca3-11e8-9dd4-46e0b9e0b654.gif)

### Steps to Reproduce

1. Create a file with the flow pragma
2. Verify the grammar shows as `Flow Javascript`
3. Notice that indentation is wonky, as shown in the gif above.

**Expected behavior:** [What you expect to happen]
I expect the closing parenthesis to be on the same column as the first character of the line with the opening parenthesis.

**Actual behavior:** [What actually happens]
The closing parens is indented by one level, to the same position as the cursor.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.32.0-beta3
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0-beta3
python 2.7.10
git 2.19.1

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

Because this `language-javascript` grammar doesn't provide a "Flow JavaScript" language, it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by Arcanemagus** [comment]
After some further discussion it was discovered that this is actually coming from the [language-typescript](https://github.com/atom/language-typescript) repository. Would you mind reopening this there?

**Comment by IanVS** [comment]
Thanks for helping me track down where this was coming from, @Arcanemagus.
