### ISSUE TITLE
Snippets don't work with flow 

### ISSUE THREAD

**Issue by joshg111** [atom/language-javascript#621]
I just installed atom and opened a javascript file. The snippets work at first. When I add the flow annotation at the top it doesn't work. The snippet doesn't show up in the autocomplete drop down.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
