### ISSUE TITLE
Swap var by let in for snippets

### ISSUE THREAD

**Issue by TiphaineLAURENT** [atom/language-javascript#655]
## Summary

Since var should not be used, or in very extremely rare cases, it should be replaced by let.

## Motivation

Better optimisation, and good practices.

## Describe alternatives you've considered

I put "for" in the title, but it should be applicate to other snippets to. Even replacing var / let by const when possible.

## Additional context

`
for (var i = 0; i < array.length; i++) {
  array[i]
}
`
replaced by
`
for (let i = 0; i < array.length; i++) {
  array[i]
}
`

**Comment by rsese** [comment]
Thanks for the suggestion!

We generally don't accept modifications for snippets in the language packages since they are easily overridden and we expect that people will do so for their own purposes. You can find instructions on how to create your own snippets in the Flight Manual. Viewing a language package that provides snippets allows you to copy the current version as a starting place for creating your own.

Thanks again for the suggestion but we're going to leave things as they are for now unless the current snippet produces invalid code.
